services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql_docker
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: cafeOrder
      MYSQL_ROOT_PASSWORD: cafe
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
